In [2]:
import tensorflow as tf

In [50]:
def smartPrinter(arg1):
     print("---/\---")
     print(sess.run(arg1,feed_dict = feed_dict))
     print("---\/---")
    
with tf.Graph().as_default() as g:
    with tf.Session() as sess:
        input = tf.placeholder(dtype=tf.float32)
        output = tf.placeholder(dtype=tf.float32)
        raw_input_data = [[10,7],[5,4],[8,3],[2,8],[4,8],[9,1],[6,8],[1,7],[5,3],[7,6]]
        raw_output_data =[[97],[71],[74],[78],[90],[68],[95],[65],[70],[82]]
        feed_dict = {input:raw_input_data,output:raw_output_data}
        num_neurons_1 = 2
        num_neurons_2 = 3
        num_neurons_3 = 1
        #print(lst_input)
        normalized_input = input / tf.reduce_max(input,0)
        normalized_output = output / tf.reduce_max(output,0)
       # m_1 = tf.reduce_max(input,0)
       # m_2 = tf.reduce_max(output,0)
       # print(m_1)
       # print(m_2)
        weights_1 = tf.Variable(tf.random_normal([2,3]))
        bias_1 = tf.Variable(tf.random_normal([3]))
        
        weighted_sum = tf.matmul(normalized_input,weights_1) + bias_1
        
        activation_1 = tf.sigmoid(weighted_sum)
        
        weights_2 = tf.Variable(tf.random_normal([3,1]))
        bias_2 = tf.Variable(0.0)
        
        weighted_sum_2 = tf.matmul(activation_1,weights_2) + bias_2
        
        activation_2 = tf.sigmoid(weighted_sum_2)
        
        loss = tf.reduce_sum((activation_2 - normalized_output)**2)/10
        
        training_step = tf.train.GradientDescentOptimizer(learning_rate=0.02).minimize(loss)
        
        sess.run(tf.global_variables_initializer())
        smartPrinter(weights_1)
        smartPrinter(weights_2)
        for i in range(100):
            sess.run(training_step,feed_dict = feed_dict)

            smartPrinter(weights_1)
            smartPrinter(weights_2)
        smartPrinter(loss)
        smartPrinter(normalized_output)
        smartPrinter(activation_2)
        #print(sess.run(weighted_sum))

---/\---
[[ 0.71784991  0.03606452  0.98351395]
 [-2.20002913 -0.01854818  0.39836469]]
---\/---
---/\---
[[-0.487396  ]
 [-1.52046335]
 [ 0.16583937]]
---\/---
---/\---
[[ 0.71768486  0.03560714  0.9835735 ]
 [-2.20017743 -0.01912005  0.39844322]]
---\/---
---/\---
[[-0.48672575]
 [-1.51696026]
 [ 0.16912332]]
---\/---
---/\---
[[ 0.71751964  0.03514905  0.98363435]
 [-2.20032597 -0.0196927   0.39852351]]
---\/---
---/\---
[[-0.48605394]
 [-1.51344872]
 [ 0.17241608]]
---\/---
---/\---
[[ 0.71735424  0.03469027  0.98369658]
 [-2.2004745  -0.02026612  0.39860556]]
---\/---
---/\---
[[-0.48538062]
 [-1.50992894]
 [ 0.17571747]]
---\/---
---/\---
[[ 0.71718866  0.03423084  0.98376012]
 [-2.20062327 -0.02084026  0.39868936]]
---\/---
---/\---
[[-0.48470581]
 [-1.50640106]
 [ 0.17902736]]
---\/---
---/\---
[[ 0.7170229   0.03377079  0.98382503]
 [-2.20077205 -0.02141508  0.39877492]]
---\/---
---/\---
[[-0.48402956]
 [-1.50286531]
 [ 0.18234558]]
---\/---
---/\---
[[ 0.71685702  0.03331015

In [49]:
       10       |      7        |     97
        5       |      4        |     71
        8       |      3        |     74
        2       |      8        |     78
        4       |      8        |     90
        9       |      1        |     68
        6       |      8        |     95
        1       |      7        |     65
        5       |      3        |     70
        7       |      6        |     82
----------------------------------------

IndentationError: unexpected indent (<ipython-input-49-e1208308c5c1>, line 2)